##
# Created by brightSPARK Labs
# www.brightsparklabs.com
##

name: Publish
on:
  push:
    branches:
      - master

jobs:
  Publish:
    uses: brightsparklabs/github-actions/.github/workflows/gradle-plugins.yml@master
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write