##
# Created by brightSPARK Labs
# www.brightsparklabs.com
##

name: Publish
on:
  push:
    branches:
      - master

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Fetch all commits to ensure `git describe` returns correct version.
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "temurin"
      - name: Publish Plugins
        run: |
          mkdir -p ~/.gradle
          echo "gradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }}" >> ~/.gradle/gradle.properties
          echo "gradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}" >> ~/.gradle/gradle.properties
          ./gradlew publishPlugins
