##
# Created by brightSPARK Labs
# www.brightsparklabs.com
##

name: Unit-Tests
on: [push]

jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: "temurin"
      - name: Test with Gradle
        run: ./gradlew build
